name: NarrowtuxLib
version: 1.2.0
author: narrowtux
description: Library that provides translation, notification, register, and other API functions to Bukkit-based plugins.

softdepend: [Spout, Register]

main: com.narrowtux.narrowtuxlib.NarrowtuxLib

commands:
    notification:
        aliases: nt
        description: View list of notifications or a specific notification ID.
        usage: /<command> [id]
